### ISSUE TITLE
Content?

### ISSUE THREAD

**Issue by martinferianc** [KuboBahyl/union-hackaton#1]
Where is the kode?

**Comment by KuboBahyl** [comment]
Right now we are dealing with ciz_tzz and dok_kod_pzs_lkr_pzs datasets. Stay tuned!

**Comment by martinferianc** [comment]
Still no kontent. Issue big.

**Comment by KuboBahyl** [comment]
preparing powerpoint, no time for dev business. Please stay in touch. Regards.

**Comment by martinferianc** [comment]
Very good, fingers crossed for d pPt.

**Comment by KuboBahyl** [comment]
Kontent here

**Comment by martinferianc** [comment]
Very kontent

**Comment by KuboBahyl** [comment]
Happy hearing that my friend. Adios
